# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_LoHHMLTS-1AB3hHpfRBoRJbwjyArXa
"""

print("tela de cadastro")

falha = False

User = input("Nome de usuário: ")
if len(User) < 3:
  print("o nome de usuário deve conter no mínimo 3 caracteres!")
  falha = True

Code = input("senha: ")
if not (Code.isdigit()):
  print("Apenas numeros são aceitos!")
  falha = True

if not (len(Code) == 6):
    print("Sua senha deve ter seis digitos!")
    falha = True

if not falha:
  print("você foi cadastrado com sucesso!")
else:
    print("por favor, refaça!")